package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/didvc/uptime-mon/internal/endpoints"
	"github.com/didvc/uptime-mon/internal/importer"
	"github.com/didvc/uptime-mon/internal/model"
)

func cmdImport(args []string) error {
	fs := newFlagSet("import", "Convert an Uptime Kuma backup export into an endpoints.txt.\n\n"+
		"Only http, keyword, ping and port monitors are convertible; anything\n"+
		"else is listed as a warning and skipped rather than half-translated.")

	in := fs.String("in", "", "Kuma backup JSON (default: the newest *.json under .personal/)")
	out := fs.String("out", "endpoints.txt", "file to write; - writes to stdout")
	includeInactive := fs.Bool("include-inactive", false,
		"also import paused monitors, written out as enabled=false")
	only := fs.String("only", "", "comma-separated Kuma monitor types to keep, e.g. http,keyword")
	groupFrom := fs.String("group-from", "tag", "where the group tag comes from: tag, parent or none")
	defaultGroup := fs.String("group", "", "group for monitors with no tag or parent")
	force := fs.Bool("force", false, "overwrite the output file if it exists")
	dryRun := fs.Bool("dry-run", false, "print what would be written without writing it")
	if err := fs.Parse(args); err != nil {
		return err
	}

	path := *in
	if path == "" {
		found, err := findBackup()
		if err != nil {
			return err
		}
		path = found
		fmt.Fprintf(os.Stderr, "uptime-mon: using %s\n", path)
	}

	opts := importer.Options{
		IncludeInactive: *includeInactive,
		GroupFrom:       *groupFrom,
		DefaultGroup:    *defaultGroup,
	}
	if *only != "" {
		opts.OnlyTypes = strings.Split(*only, ",")
	}

	targets, warnings, err := importer.LoadFile(path, opts)
	if err != nil {
		return err
	}

	for _, w := range warnings {
		fmt.Fprintf(os.Stderr, "  skipped %s\n", w)
	}
	summarise(targets, warnings)

	header := fmt.Sprintf(
		"generated by uptime-mon %s on %s\nsource: %s\nedit freely: this file is the source of truth, not the backup",
		version, time.Now().Format("2006-01-02 15:04"), filepath.Base(path))

	if *dryRun || *out == "-" {
		return endpoints.Render(os.Stdout, targets, header)
	}

	if _, err := os.Stat(*out); err == nil && !*force {
		return fmt.Errorf("%s already exists; pass -force to overwrite, or -out to write elsewhere", *out)
	}

	// Write via a temp file so a failure cannot leave a half-written
	// endpoints.txt where a complete one used to be.
	tmp, err := os.CreateTemp(filepath.Dir(*out), ".endpoints-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if err := endpoints.Render(tmp, targets, header); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	// Re-read what we just wrote: if it does not parse, the import is a bug
	// and the user should hear about it now rather than at the first run.
	if _, err := endpoints.LoadFile(tmpName, endpoints.BaseDefaults()); err != nil {
		return fmt.Errorf("generated file does not parse (this is a bug): %w", err)
	}
	if err := os.Rename(tmpName, *out); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
	return nil
}

func summarise(targets []model.Target, warnings []importer.Warning) {
	byKind := map[model.Kind]int{}
	byGroup := map[string]int{}
	enabled := 0
	for _, t := range targets {
		byKind[t.Kind]++
		byGroup[t.Group]++
		if t.Enabled {
			enabled++
		}
	}

	kinds := make([]string, 0, len(byKind))
	for k, n := range byKind {
		kinds = append(kinds, fmt.Sprintf("%s=%d", k, n))
	}
	sort.Strings(kinds)

	fmt.Fprintf(os.Stderr, "imported %d monitor(s): %s\n", len(targets), strings.Join(kinds, " "))
	fmt.Fprintf(os.Stderr, "  %d enabled, %d disabled", enabled, len(targets)-enabled)
	if len(warnings) > 0 {
		fmt.Fprintf(os.Stderr, ", %d skipped", len(warnings))
	}
	fmt.Fprintln(os.Stderr)

	if len(byGroup) > 1 {
		groups := make([]string, 0, len(byGroup))
		for g, n := range byGroup {
			if g == "" {
				g = "(none)"
			}
			groups = append(groups, fmt.Sprintf("%s=%d", g, n))
		}
		sort.Strings(groups)
		fmt.Fprintf(os.Stderr, "  groups: %s\n", strings.Join(groups, " "))
	}
}

// findBackup locates the newest JSON export under .personal/, which is where
// a Kuma backup lands if you just dropped it next to the project.
func findBackup() (string, error) {
	for _, dir := range []string{".personal", "."} {
		ents, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		var best string
		var bestMod time.Time
		for _, e := range ents {
			if e.IsDir() || !strings.HasSuffix(strings.ToLower(e.Name()), ".json") {
				continue
			}
			info, err := e.Info()
			if err != nil {
				continue
			}
			if best == "" || info.ModTime().After(bestMod) {
				best, bestMod = filepath.Join(dir, e.Name()), info.ModTime()
			}
		}
		if best != "" {
			return best, nil
		}
	}
	return "", fmt.Errorf("no backup JSON found in .personal/ or the current directory; pass -in")
}
