package endpoints

import (
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/didvc/uptime-mon/internal/model"
)

func TestParseBasics(t *testing.T) {
	src := `
# a comment
https://example.com/

# defaults apply from here down
defaults interval=30s timeout=5s group=prod

https://example.com/health   name="API health" keyword="all systems go"
ping://8.8.8.8               name=dns
tcp://db.internal:5432       timeout=2s
example.org                  # bare host becomes https
https://a.example/           expect=200-299,404 insecure retries=2 retry_interval=3s
https://b.example/           header="X-Key: abc def" method=POST body='{"a":1}'
https://off.example/         enabled=false
`
	got, err := Parse(strings.NewReader(src), BaseDefaults())
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 8 {
		t.Fatalf("got %d targets", len(got))
	}

	// The first target predates the defaults line, so it keeps the baseline.
	if got[0].Interval != 60*time.Second || got[0].Group != "" {
		t.Errorf("pre-defaults target = %+v", got[0])
	}
	if got[1].Interval != 30*time.Second || got[1].Group != "prod" {
		t.Errorf("post-defaults target = %+v", got[1])
	}
	if got[1].Name != "API health" || got[1].Keyword != "all systems go" ||
		got[1].Kind != model.KindKeyword {
		t.Errorf("keyword target = %+v", got[1])
	}
	if got[2].Kind != model.KindPing || got[2].Host != "8.8.8.8" || got[2].Name != "dns" {
		t.Errorf("ping target = %+v", got[2])
	}
	if got[3].Kind != model.KindTCP || got[3].Port != 5432 || got[3].Timeout != 2*time.Second {
		t.Errorf("tcp target = %+v", got[3])
	}
	if got[4].URL != "https://example.org" {
		t.Errorf("bare host = %q", got[4].URL)
	}
	if got[5].Accept.String() != "200-299,404" || !got[5].Insecure ||
		got[5].Retries != 2 || got[5].RetryInterval != 3*time.Second {
		t.Errorf("options target = %+v", got[5])
	}
	if len(got[6].Headers) != 1 || got[6].Headers[0].Value != "abc def" ||
		got[6].Method != "POST" || got[6].Body != `{"a":1}` {
		t.Errorf("header target = %+v", got[6])
	}
	if got[7].Enabled {
		t.Errorf("expected disabled: %+v", got[7])
	}
}

func TestParseErrors(t *testing.T) {
	for _, src := range []string{
		`https://x/ interval=0`,
		`https://x/ bogus=1`,
		`https://x/ name="unterminated`,
		`ftp://x/`,
		`ping://`,
		`tcp://host`,
		`tcp://host:notaport`,
		`https://x/ expect=299-200`,
		`defaults name=nope`,
	} {
		if _, err := Parse(strings.NewReader(src), BaseDefaults()); err == nil {
			t.Errorf("Parse(%q) should have failed", src)
		}
	}
	if _, err := Parse(strings.NewReader("# only comments\n"), BaseDefaults()); err == nil {
		t.Error("empty file should error")
	}
}

func TestDuplicateNamesAreDisambiguated(t *testing.T) {
	src := "https://x/ name=dup\nhttps://y/ name=dup\nhttps://z/ name=dup\n"
	got, err := Parse(strings.NewReader(src), BaseDefaults())
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"dup", "dup#2", "dup#3"}
	for i, w := range want {
		if got[i].Name != w {
			t.Errorf("name[%d] = %q, want %q", i, got[i].Name, w)
		}
	}
}

func TestCommentAndQuoteHandling(t *testing.T) {
	src := `https://x/#frag  name="has # hash"  # trailing comment
https://y/ keyword="say \"hi\" now"
`
	got, err := Parse(strings.NewReader(src), BaseDefaults())
	if err != nil {
		t.Fatal(err)
	}
	if got[0].URL != "https://x/#frag" {
		t.Errorf("fragment lost: %q", got[0].URL)
	}
	if got[0].Name != "has # hash" {
		t.Errorf("name = %q", got[0].Name)
	}
	if got[1].Keyword != `say "hi" now` {
		t.Errorf("keyword = %q", got[1].Keyword)
	}
}

func TestQuote(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"plain", "plain"},
		{"", `""`},
		{"has space", `"has space"`},
		{`has"quote`, `"has\"quote"`},
		{`back\slash`, `"back\\slash"`},
		{"hash#here", `"hash#here"`},
	} {
		if got := Quote(c.in); got != c.want {
			t.Errorf("Quote(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestRenderRoundTrip(t *testing.T) {
	src := `
defaults interval=60s timeout=48s group=web

https://example.com/
https://example.com/health   name="API health" keyword="all systems go" interval=30s
https://weird.example/       keyword="quotes \" and 'single' and #hash" invert=true
ping://8.8.8.8               name=dns group=net
tcp://db.internal:5432       group=db timeout=2s
https://a.example/           expect=200-299,404 insecure=true retries=2 retry_interval=3s
https://b.example/           header="X-Key: abc def" header="Cookie: session=abc123" method=POST body='{"a":1}'
https://off.example/         enabled=false upside_down=true redirects=0
`
	first, err := Parse(strings.NewReader(src), BaseDefaults())
	if err != nil {
		t.Fatal(err)
	}

	var buf strings.Builder
	if err := Render(&buf, first, "generated by a test"); err != nil {
		t.Fatal(err)
	}

	second, err := Parse(strings.NewReader(buf.String()), BaseDefaults())
	if err != nil {
		t.Fatalf("re-parsing rendered output failed: %v\n---\n%s", err, buf.String())
	}

	// Render groups targets, so compare as sets keyed by name.
	if len(first) != len(second) {
		t.Fatalf("count %d -> %d\n%s", len(first), len(second), buf.String())
	}
	byName := map[string]model.Target{}
	for _, x := range second {
		byName[x.Name] = x
	}
	for _, want := range first {
		got, ok := byName[want.Name]
		if !ok {
			t.Errorf("target %q disappeared\n%s", want.Name, buf.String())
			continue
		}
		// UserAgent and MaxBody are process-level settings, not per-target
		// ones, so Render does not emit them.
		got.UserAgent, want.UserAgent = "", ""
		got.MaxBody, want.MaxBody = 0, 0
		if !reflect.DeepEqual(got, want) {
			t.Errorf("round trip changed %q:\n got %+v\nwant %+v\n---\n%s",
				want.Name, got, want, buf.String())
		}
	}
}

func TestFilter(t *testing.T) {
	in := []model.Target{
		{Name: "alpha", Group: "prod", Enabled: true},
		{Name: "beta", Group: "dev", Enabled: true},
		{Name: "gamma", Group: "prod", Enabled: false},
	}
	if got := Filter(in, "prod", "", false); len(got) != 2 {
		t.Errorf("group filter got %d", len(got))
	}
	if got := Filter(in, "prod", "", true); len(got) != 1 {
		t.Errorf("enabled-only filter got %d", len(got))
	}
	if got := Filter(in, "", "ET", false); len(got) != 1 || got[0].Name != "beta" {
		t.Errorf("name filter got %+v", got)
	}
	if got := Filter(in, "", "", false); len(got) != 3 {
		t.Errorf("no filter got %d", len(got))
	}
}
